# Generated by Django 6.0.4 on 2026-04-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopCRM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
