# Generated by Django 6.0.4 on 2026-04-18 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopCRM', '0002_remove_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва категорії')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис (для розмірів/деталей)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shopCRM.category', verbose_name='Батьківська категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('description', models.TextField(blank=True, verbose_name='Опис товару')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='Розмір (см, мм, шт)')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Собівартість')),
                ('drop_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Дроп ціна')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна продажу')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopCRM.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
    ]
