# Generated by Django 6.0.4 on 2026-04-19 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopCRM', '0003_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='По батькові')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('region', models.CharField(max_length=100, verbose_name='Область')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('post_department', models.CharField(max_length=255, verbose_name='Відділення')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number_global', models.CharField(max_length=50, unique=True, verbose_name='Глобальний №')),
                ('delivery_service', models.CharField(choices=[('nova_poshta', 'Нова Пошта'), ('ukr_poshta', 'Укрпошта'), ('self_pickup', 'Самовивіз'), ('other', 'Інша служба')], default='nova_poshta', max_length=20, verbose_name='Служба доставки')),
                ('ttn', models.CharField(blank=True, max_length=50, null=True, verbose_name='ТТН')),
                ('engraving_description', models.TextField(blank=True, verbose_name='Опис гравіювання')),
                ('customer_request', models.TextField(blank=True, verbose_name='Прохання клієнта')),
                ('price_wholesale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оптова ціна')),
                ('price_selling', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна продажу')),
                ('prepayment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Передоплата')),
                ('is_cod', models.BooleanField(default=True, verbose_name='Наложка')),
                ('status', models.CharField(choices=[('manufacturing', 'Виготовлення'), ('packaging', 'Комплектація'), ('shipped', 'Передано в службу доставки'), ('received', 'Отримано'), ('canceled', 'Скасовано')], default='manufacturing', max_length=50, verbose_name='Статус')),
                ('delivery_status_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopCRM.client', verbose_name='Клієнт')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('price_at_moment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (на момент замовлення)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopCRM.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopCRM.product', verbose_name='Товар')),
            ],
        ),
    ]
