# Generated by Django 6.0.4 on 2026-04-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopCRM', '0004_client_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('olx', 'OLX'), ('prom', 'Prom'), ('other', 'Інша')], default='olx', max_length=20, verbose_name='Платформа'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Собівартість (дроп)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_moment',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна продажу'),
        ),
    ]
